export const MOCK_ADD_PASSWORD = 'MOCK_ADD_PASSWORD';
export const MOCK_EDIT_PASSWORD = 'MOCK_EDIT_PASSWORD';
export const MOCK_DELETE_PASSWORD = 'MOCK_DELETE_PASSWORD';

export const FETCH_MASTER_PASSWORD = 'FETCH_MASTER_PASSWORD';